"""Added Refund model

Revision ID: 12768a0eaba9
Revises: ac0b82b5e94b
Create Date: 2025-03-27 00:19:52.042292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12768a0eaba9'
down_revision = 'ac0b82b5e94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refund_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('refund_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['return_id'], ['return.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refund')
    # ### end Alembic commands ###
