"""Added Supplier model

Revision ID: 3735b5e81c89
Revises: f2a43036a850
Create Date: 2025-03-25 15:11:36.047838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3735b5e81c89'
down_revision = 'f2a43036a850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint('FK__order_ite__order__02FC7413', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__order_ite__order__02FC7413', 'order', ['order_id'], ['id'])

    op.drop_table('supplier')
    # ### end Alembic commands ###
