"""Added ProductSupplier model

Revision ID: 383411752db6
Revises: dd0257461c48
Create Date: 2025-03-25 17:41:14.941957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383411752db6'
down_revision = 'dd0257461c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_supplier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_supplier',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('supply_date', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='FK__product_s__produ__29221CFB'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name='FK__product_s__suppl__2A164134'),
    sa.PrimaryKeyConstraint('id', name='PK__product___3213E83FC794DAB8')
    )
    # ### end Alembic commands ###
