"""Add discount_id to orders

Revision ID: c57be5d56e0b
Revises: 12768a0eaba9
Create Date: 2025-05-19 22:12:13.252739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57be5d56e0b'
down_revision = '12768a0eaba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'discount', ['discount_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('discount_id')

    # ### end Alembic commands ###
