"""add receipts-settings table

Revision ID: d504d110b14d
Revises: 4d8ae38a0a2e
Create Date: 2025-05-26 22:48:07.944156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd504d110b14d'
down_revision = '4d8ae38a0a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=100), nullable=False),
    sa.Column('header_text', sa.String(length=255), nullable=True),
    sa.Column('footer_text', sa.String(length=255), nullable=True),
    sa.Column('legal_text', sa.String(length=255), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt_settings')
    # ### end Alembic commands ###
